DROP TABLE GS_USER;
DROP TABLE GS_GAME;
DROP TABLE GS_LEADERBOARD;
DROP TABLE GS_PARTICIPANT;
DROP TABLE GS_MATCH;
DROP TABLE GS_HISTORY;

CREATE TABLE GS_USER (
  NICKNAME VARCHAR(15) PRIMARY KEY,
  PASSWORD VARCHAR(160),
  ADMIN BOOLEAN,
  EMAIL VARCHAR(30)
);

CREATE TABLE GS_GAME (
  NAME VARCHAR(25) PRIMARY KEY,
  MINPLAYER INT NOT NULL,
  MAXPLAYER INT NOT NULL
);

CREATE TABLE GS_LEADERBOARD (
  USER VARCHAR(15) NOT NULL,
  GAME VARCHAR(25) NOT NULL,
  ELO INT
);

CREATE TABLE GS_MATCH (
  ID INT NOT NULL AUTO_INCREMENT,
  GAME VARCHAR(25),
  DATESTAMP DATETIME NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE GS_PARTICIPANT (
  USER_ID VARCHAR(15) NOT NULL,
  MATCH_ID INT NOT NULL,
  TEAM INT,
  PLACE INT,
  ELO_FOR_MATCH INT
);

CREATE TABLE GS_HISTORY (
  USER_ID VARCHAR(15) NOT NULL,
  MATCH_ID INT NOT NULL,
  TURN INT NOT NULL,
  DESCRIPTION VARCHAR(200) NOT NULL,
  DATESTAMP DATETIME NOT NULL
);

INSERT INTO GS_GAME (NAME, MINPLAYER, MAXPLAYER) VALUES ('szachy', 2, 2);
INSERT INTO GS_GAME (NAME, MINPLAYER, MAXPLAYER) VALUES ('kosci', 1, 6);
INSERT INTO GS_GAME (NAME, MINPLAYER, MAXPLAYER) VALUES ('warcaby', 2, 2);
INSERT INTO GS_GAME (NAME, MINPLAYER, MAXPLAYER) VALUES ('chinczyk', 2, 4);
